### ISSUE TITLE
Rework the deprecation process

### ISSUE THREAD

**Issue by MGaetan89** [robolectric/robolectric.github.io#199]
Based on the discussion in https://github.com/robolectric/robolectric/pull/8810, I think it would make sense to rework the [Deprecations and Backwards Compatibility](https://robolectric.org/contributing/#deprecations-and-backwards-compatibility) section of the documentation.
Instead of removing deprecated code in the next minor version, they are removed based on usages (from what I understood).

https://github.com/robolectric/robolectric.github.io/blob/dc970c5e7030cfeb6dd104a44c3aff0b3d81d308/contributing.md?plain=1#L63

Maybe a more streamlined approach could be that anything deprecated in version x.y.z will be removed in (x + 1).0.0. What do you think?
We could then updated all the current deprecated code to say they they will be removed in Robolectric 5.0.0.

**Comment by hoisie** [comment]
@MGaetan89 it is often difficult to remove deprecated methods. For instance, the legacy looper mode has been deprecated for years, but there are many of tests at Google that use it. This is because it is sometimes nontrivial to convert tests to use PAUSED looper mode, and sometimes code gets into maintenance mode and people don't actively invest in cleaning it up.

**Comment by MGaetan89** [comment]
I started to understand as much by contributing on various part of the project 🙂 
I think we can close this issue, since there doesn't seem anything to do here in the end.
